version: '3'
services:
  catalogue:
    image: catalogue
    build: ./catalogue
    ports:
      - "9081:9081"
    volumes:
      - "./catalogue:/usr/src/app"
      - "/usr/src/app/node_modules"
  shop:
    image: shop
    build: ./shop
    ports:
      - "9083:9083"
    links:
      - catalogue
    environment:
      CATALOGUE_HOST: catalogue
    volumes:
      - "./shop:/usr/src/app"
      - "/usr/src/app/node_modules"
